<?php
use App\ItemType;
use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
class ItemtypeTableSeeder extends Seeder {
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		//delete users table records
		DB::table('itemtype')->delete();
		DB::table('itemtype')->truncate();
		//insert some dummy records
ItemType::create(array( 'itemtype' => 'ACETATE, TRANSPARENT, 1.20 MTRS, MIN, WIDTH, 50/MTRS', 'description' => ''));
ItemType::create(array( 'itemtype' => 'AIR FRESHENER, BAYFRESH', 'description' => ''));
ItemType::create(array( 'itemtype' => 'ALCOHOL, RUBBING 70%', 'description' => ''));
ItemType::create(array( 'itemtype' => 'AUDIO CASSETTE TAPE BLANK ELECTRA 90 MIN', 'description' => ''));
ItemType::create(array( 'itemtype' => 'BALLAST, 18WATTS', 'description' => ''));
ItemType::create(array( 'itemtype' => 'BALLAST, 36WATTS', 'description' => ''));
ItemType::create(array( 'itemtype' => 'BALLAST, 40WATTS', 'description' => ''));
ItemType::create(array( 'itemtype' => 'BALL PEN, BLACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'BALL PEN, BLUE', 'description' => ''));
ItemType::create(array( 'itemtype' => 'BALL PEN, RED', 'description' => ''));
ItemType::create(array( 'itemtype' => 'BATTERY, AA / 1.5 VOLTS (2PCS/ PACK)', 'description' => ''));
ItemType::create(array( 'itemtype' => 'BATTERY, AAA / 1.5 VOLTS (2PCS/ PACK)', 'description' => ''));
ItemType::create(array( 'itemtype' => 'BINDER, TB, "11 x 14-7/8"', 'description' => ''));
ItemType::create(array( 'itemtype' => 'BATTERY, DRY CELL D, 1.5', 'description' => ''));
ItemType::create(array( 'itemtype' => 'CALCULATOR, SCIENTIFIC', 'description' => ''));
ItemType::create(array( 'itemtype' => 'CARBON FILM, PE, BLACK, 216X330 (LONG)', 'description' => ''));
ItemType::create(array( 'itemtype' => 'CARTOLINA, ASSORTED COLORS', 'description' => ''));
ItemType::create(array( 'itemtype' => 'CARTOLINA, WHITE', 'description' => ''));
ItemType::create(array( 'itemtype' => 'CD, REWRITABLE', 'description' => ''));
ItemType::create(array( 'itemtype' => 'CHALK WHITE DUSTLESS, DURA SMOOTH, 100/BXS ', 'description' => ''));
ItemType::create(array( 'itemtype' => 'CLIP PAPER, GEM TYPE 33MM, VINYL COATED, 100/BOX RAINBOW', 'description' => ''));
ItemType::create(array( 'itemtype' => 'CLIP PAPER, GEM TYPE 50MM, VINYL COATED, 100/BOX RAINBOW', 'description' => ''));
ItemType::create(array( 'itemtype' => 'CLIP, BACKFOLD, 19MM  ALL METAL, 12PCS/BOX', 'description' => ''));
ItemType::create(array( 'itemtype' => 'CLIP, BACKFOLD, 25MM  ALL METAL, 12PCS/BOX', 'description' => ''));
ItemType::create(array( 'itemtype' => 'COLUMNAR 6 COLUMS', 'description' => ''));
ItemType::create(array( 'itemtype' => 'COMPACT DISC. REWRITABLE (CD-RW) 700MB MINS CAP. 80MINS REC.', 'description' => ''));
ItemType::create(array( 'itemtype' => 'COMPUTER CONTINUOUS FORMS,  3 PLY, PLAIN ,  PLAIN , 11" X 9-1/2, 280X 241MM', 'description' => ''));
ItemType::create(array( 'itemtype' => 'COMPUTER CONTINUOUS FORMS, 1 PLY, PLAIN , 11" X 14-7/8, 280X378MM', 'description' => ''));
ItemType::create(array( 'itemtype' => 'COMPUTER CONTINUOUS FORMS, 1 PLY, PLAIN , 11" X 9-1/2,  280X 241MM', 'description' => ''));
ItemType::create(array( 'itemtype' => 'COMPUTER FORMS, 1 PLY, 3-2/3 x 8', 'description' => ''));
ItemType::create(array( 'itemtype' => 'COMPUTER CONTINUOUS FORMS, 2  PLY, PLAIN , 11" X 9-1/2,  241mm x 280mm', 'description' => ''));
ItemType::create(array( 'itemtype' => 'COMPUTER  CONTINUOUS FORMS, 2 PLY, PLAIN , 11" X 14-7/9,  280mm x 378mm ', 'description' => ''));
ItemType::create(array( 'itemtype' => 'COMPUTER FORMS, 3 PLY, PLAIN , 11" X 9-1/4', 'description' => ''));
ItemType::create(array( 'itemtype' => 'COMPUTER FORMS, 3 PLY, PLAIN , 11" X 14-7/8"', 'description' => ''));
ItemType::create(array( 'itemtype' => 'CORRECTION FLUID WATER BASE 15 ML', 'description' => ''));
ItemType::create(array( 'itemtype' => 'CORRECTION TAPE, DISPOSABLE, USABLE LENGTH OF 6MTRS, THICKNESS', 'description' => ''));
ItemType::create(array( 'itemtype' => 'CUTTTER, BLADE (10PCS/PACK)', 'description' => ''));
ItemType::create(array( 'itemtype' => 'CUTTER, GEN. PURPOSE, HEAVY DUTY BUILT-IN W/ METAL SLIDING GUIDE W/ SCREW', 'description' => ''));
ItemType::create(array( 'itemtype' => 'COMPACT FLOURESCENT LAMP (CFL) 18 watts', 'description' => ''));
ItemType::create(array( 'itemtype' => 'CARBON FILM, PE, BLACK, 216X279 (SHORT)', 'description' => ''));
ItemType::create(array( 'itemtype' => 'CLIP, BACKFOLD, 19MM ALL METAL, 12PCS/BOX', 'description' => ''));
ItemType::create(array( 'itemtype' => 'CLIP, BACKFOLD, 32MM  ALL METAL, 12PCS/BOX', 'description' => ''));
ItemType::create(array( 'itemtype' => 'CLIP, BACKFOLD, 50MM  ALL METAL, 12PCS/BOX', 'description' => ''));
ItemType::create(array( 'itemtype' => 'CALCULATOR, PALM SIZE PRINTING CANON', 'description' => ''));
ItemType::create(array( 'itemtype' => 'CALCULATOR, COMPACT, 12 DIGITS AD- RITE', 'description' => ''));
ItemType::create(array( 'itemtype' => 'CALCULATOR, COMPACT, 12 DIGITS CANON', 'description' => ''));
ItemType::create(array( 'itemtype' => 'DVD, REWRITABLE ', 'description' => ''));
ItemType::create(array( 'itemtype' => 'DATA FOLDER, LONG; DATA FILE BOX, made of chipboard, with closed ends', 'description' => ''));
ItemType::create(array( 'itemtype' => 'DATING/STAMPING MACHINE', 'description' => ''));
ItemType::create(array( 'itemtype' => 'DISINFECTANT SPRAY , aerosol, 400-550 grams', 'description' => ''));
ItemType::create(array( 'itemtype' => 'ENVELOPE DOCUMENTARY FOR LEGAL SIZE DOCU MENT KRAFT, 150GSM / 254MMX381MM', 'description' => ''));
ItemType::create(array( 'itemtype' => 'ENVELOPE DOCUMENTARY SHORT 150 GSM 9" X 12"', 'description' => ''));
ItemType::create(array( 'itemtype' => 'ENVELOPE EXPANDING, LONG ', 'description' => ''));
ItemType::create(array( 'itemtype' => 'ENVELOPE EXPANDING, SHORT', 'description' => ''));
ItemType::create(array( 'itemtype' => 'ENVELOPE, MAILING, WHITE 500/BX, SHORT', 'description' => ''));
ItemType::create(array( 'itemtype' => 'ENVELOPE, MAILING, WHITE,  500/BX LONG', 'description' => ''));
ItemType::create(array( 'itemtype' => 'ERASER, BLACKBOARD, FELT', 'description' => ''));
ItemType::create(array( 'itemtype' => 'ERASER, PLASTIC; FLUORESCENT RUBBER TIPPED PENCIL', 'description' => ''));
ItemType::create(array( 'itemtype' => 'ENVELOPE, MAILING, WINDOW,  WHITE,  500/BX LONG', 'description' => ''));
ItemType::create(array( 'itemtype' => 'FAN, ORBIT TYPE 16"', 'description' => ''));
ItemType::create(array( 'itemtype' => 'FAN, ORBIT TYPE 18"', 'description' => ''));
ItemType::create(array( 'itemtype' => 'FAN, STAND TYPE', 'description' => ''));
ItemType::create(array( 'itemtype' => 'FAN, INDUSTRIAL FLOOR TYPE', 'description' => ''));
ItemType::create(array( 'itemtype' => 'FAN, TABLE TYPE', 'description' => ''));
ItemType::create(array( 'itemtype' => 'FAN, WALL TYPE', 'description' => ''));
ItemType::create(array( 'itemtype' => 'FOLDER, FANCY , LEGAL  SIZE PAPER DOC,50/PACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'FASTENER, METAL', 'description' => ''));
ItemType::create(array( 'itemtype' => 'FASTENER, PLASTIC PRINCE', 'description' => ''));
ItemType::create(array( 'itemtype' => 'FLASH DRIVE 16GB, USB VERSION 2.0 PORT COMPATIBLE, PLUG AND PLAY APACER BRAND', 'description' => ''));
ItemType::create(array( 'itemtype' => 'FLASH DRIVE 8GB, USB VERSION 2.0 PORT COMPATIBLE, PLUG AND PLAY APACER BRAND', 'description' => ''));
ItemType::create(array( 'itemtype' => 'FLOURESCENT LAMP TABULAR 16 WATTS', 'description' => ''));
ItemType::create(array( 'itemtype' => 'FLOURESCENT LAMP TABULAR 18 WATTS', 'description' => ''));
ItemType::create(array( 'itemtype' => 'FLOURESCENT LAMP TABULAR 28 WATTS', 'description' => ''));
ItemType::create(array( 'itemtype' => 'FLOURESCENT LAMP TABULAR 36 WATTS', 'description' => ''));
ItemType::create(array( 'itemtype' => 'FLOURESCENT LAMP TABULAR 40 WATTS', 'description' => ''));
ItemType::create(array( 'itemtype' => 'FLOURESCENT LIGHTNING FIXTURE 1X40W', 'description' => ''));
ItemType::create(array( 'itemtype' => 'FOLDER LONG TAG BOARD 14 POINTS LEGAL SIZE', 'description' => ''));
ItemType::create(array( 'itemtype' => 'FOLDER SHORT TAG BOARD 14 POINTS LETTER SIZE', 'description' => ''));
ItemType::create(array( 'itemtype' => 'FOLDER, EXPANDING, LONG', 'description' => ''));
ItemType::create(array( 'itemtype' => 'FOLDER, EXPANDING, SHORT', 'description' => ''));
ItemType::create(array( 'itemtype' => 'FOLDER, PRESSBOARD , LEGAL PAPER BOARD,100/PACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'FOLDER,  TAGBOARD, A4 SIZE DOC, 100/PACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'FLAG, PHILIPPINE (6"X3")', 'description' => ''));
ItemType::create(array( 'itemtype' => 'FOLDER, L-TYPE PLASTIC, LEGAL SIZE', 'description' => ''));
ItemType::create(array( 'itemtype' => 'GLUE', 'description' => ''));
ItemType::create(array( 'itemtype' => 'HANDBOOK ON PROCUREMENT', 'description' => ''));
ItemType::create(array( 'itemtype' => 'EXTERNAL HARD DRIVE', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INDEX CARD BOX, 4-3/8"x5-5/8" x 4"(3" x 5")', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INDEX CARD BOX, 5-3/8"x8-7/8" x 6"(5" x 8")', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INDEX TAB, SELF-ADHESIVE', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK CARTRIDGE FOR HP 840/845 #C6625A (HP 17)COLORED', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK CARTRIDGE FOR HP 840C/845 #C6615A(HP 15) BLACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK CART, HP C9352AA, (HP22), TRI-COLOR', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK CART, HP C9351AA, (HP21), BLACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK CART. FOR HP PRINTER, #1823, COLORED; INK CART. FOR HP PRINTER, #23, COLORED', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK CART, HP C8727AA (HP 27), BLACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK CART, HP Q8893AA (C8728AA), HP28, COLORED', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK CARTRIDGE, HP 45; INK CARTRIDGE FOR HP 710C/830C #51645A BLACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK CART, HP C6578DA, (HP78)  1220C, TRI-COLOR', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INKJET CARTRIDGE, BLACK #38', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INKJET CARTRIDGE, COLORED #39', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK CART, HP CC640WA, (HP60), BLACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK CART, HP CC643WA, (HP60), TRI-COLOR', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK CART HP C4906AA (HP60XL), COLORED', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK CART, HP C8767WA, (HP96), BLACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK CART, HP C9363WA, (HP97), TRI-COLOR', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK CART HP C4906AA (HP940), BLACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INKJET CARTRIDGE, HP703, BLACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INKJET CARTRIDGE, HP #CD888AA (HP703) COLORED /D730/SERIES#735', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INKJET CARTRIDGE, HP #900 COLORED', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INKJET CARTRIDGE, HP #900 BLACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INKJET CARTRIDGE HP #18, BLACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INKJET CARTRIDGE HP #18, CYAN', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INKJET CARTRIDGE HP #18, YELLOW', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INKJET CARTRIDGE HP #18, MAGENTA', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INKJET  CARTRIDGE  HP #CD972AA (HP 920XL), CYAN', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INKJET  CARTRIDGE  HP #CD973AA (HP 920XL), MAGENTA', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INKJET  CARTRIDGE  HP #CD974AA (HP 920XL), YELLOW', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INKJET  CARTRIDGE  HP #CD975AA (HP 920XL), BLACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK EPSON L110 (BLACK),  C13T664100 (T6641), BLACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK EPSON L110 (CYAN), C13T664200 (T6642), CYAN', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK EPSON L110 (MAGENTA), C13T664300 (T6643), MAGENTA', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK EPSON L110 (YELLOW),  C13T664400 (T6644), YELLOW', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK COPYPRINTER, BLACK, GESTETNER MODEL 5307/5308/3440/5430, CPi7', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK COPYPRINTER, BLACK, GESTETNER MODEL 5329, CP 12', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INKJET CARTRIDGE, HP704, BLACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INKJET CARTRIDGE, HP704, COLORED', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INKJET CARTRIDGE, HP CC653 (901) BLACK, OFFICEJET 4580', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK CART, HP CC656AA, (901) TRI-COLOR OFFICEJET 4500', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK CART. OPSCAN 4U, 51604A', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK DESKJET , CANNON FIXMA MX366 PG810 , BLACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK DESKJET , CANNON FIXMA MX366 PG811 , COLORED', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INDEX CARD,3"x 5",ruled both sides, 500s/pack', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INDEX CARD, 5" x 8",ruled both side, 500s/pack', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK DESKJET , CANON  830; INK CANNON DESKJET FIXMA Mx366 PG810, COLORED', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK DESKJET , CANON 831; INK CANNON DESKJET, FIXMA Mx366 PG810, BLACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK CARTRIDGE, ADVANTAGE HP 4625 #685, BLACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK CARTRIDGE, ADVANTAGE HP 4625 #685, CYAN', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK CARTRIDGE, ADVANTAGE HP 4625 #685, MAGENTA', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK CARTRIDGE, ADVANTAGE HP 4625 #685, YELLOW', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK CART, HP C9364WA (HP98), BLACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK DESKJET , CANON  PG40 , BLACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK DESKJET , CANON CL-41 ,COLORED', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK, DUPLO DP514', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK CART GESTETNER DX2430, BLACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK CART HP 74, BLACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INSECTICIDE, aerosol type, net content: 600ml min/can, 12 cans per box', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INKJET  CARTRIDGE,  HP #900 BLACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INKJET  CARTRIDGE, HP  #900 COLORED', 'description' => ''));
ItemType::create(array( 'itemtype' => 'LOOSELEAF COVER W/ PAPER CLOTH STRAP, GREEN 8 1/2 X 14', 'description' => ''));
ItemType::create(array( 'itemtype' => 'L-TYPE', 'description' => ''));
ItemType::create(array( 'itemtype' => 'MAGAZINE FILE, LONG', 'description' => ''));
ItemType::create(array( 'itemtype' => 'MAGAZINE FILE, SHORT', 'description' => ''));
ItemType::create(array( 'itemtype' => 'MARKER, HIGHLIGHTER ASSORTED, NON TOXIC SMELL', 'description' => ''));
ItemType::create(array( 'itemtype' => 'MARKING PEN PERMANENT BLACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'MARKING PEN PERMANENT BLUE', 'description' => ''));
ItemType::create(array( 'itemtype' => 'MARKING PEN PERMANENT RED', 'description' => ''));
ItemType::create(array( 'itemtype' => 'MARKING PEN WHITEBOARD, BLACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'MARKING PEN WHITEBOARD, BLUE', 'description' => ''));
ItemType::create(array( 'itemtype' => 'MARKING PEN WHITEBOARD, RED', 'description' => ''));
ItemType::create(array( 'itemtype' => 'MASTER COPY PRINTER, CMPT17 MODEL 5307/5308 GESTETNER ', 'description' => ''));
ItemType::create(array( 'itemtype' => 'MEDAL,GOLD, SILVER, BRONZE (ORDINARY)', 'description' => ''));
ItemType::create(array( 'itemtype' => 'MOUSE OPTICAL, USB CONNECTION TYPE, 400 DPI, PLUG AND PLAY: GENIUS NETSCROLL BRAND', 'description' => ''));
ItemType::create(array( 'itemtype' => 'MAGAZINE FILE W/ COVER, (cartile w/ operable cover holds up to A4 and Lega)', 'description' => ''));
ItemType::create(array( 'itemtype' => 'MEDAL, SIZE 4.5CM, SILVER (HONOR STUDENT)', 'description' => ''));
ItemType::create(array( 'itemtype' => 'MEDAL, SIZE 4.5CM, BRONZE (HONOR STUDENT)', 'description' => ''));
ItemType::create(array( 'itemtype' => 'MASTER COPY PRINTER, CMPT9 GESTETNER ', 'description' => ''));
ItemType::create(array( 'itemtype' => 'NOTEBOOK, STENOGRAPHIC, SPIRAL, 40 LEAVES', 'description' => ''));
ItemType::create(array( 'itemtype' => 'NOTARIAL SEAL, NO 24 SMALL BOX', 'description' => ''));
ItemType::create(array( 'itemtype' => 'NOTE PAD, stick on, 50mm x 76mm (2"x3") min', 'description' => ''));
ItemType::create(array( 'itemtype' => 'NOTE PAD, STICK-ON (3"X3") 100 SHEETS PER PAD', 'description' => ''));
ItemType::create(array( 'itemtype' => 'PAPER, MULTI-PURPOSE, LEGAL 70gsm', 'description' => ''));
ItemType::create(array( 'itemtype' => 'PAPER, MULTI-PURPOSE, LEGAL 80gsm', 'description' => ''));
ItemType::create(array( 'itemtype' => 'PAPER MULTICOPY,80GSM,216MM X279MM (SHORT)', 'description' => ''));
ItemType::create(array( 'itemtype' => 'PAPER MIMEOGRAPH GROUNDWOOD , 216MM X 330MM, 60GSM /  (8 1/4"x 13") 500 sheet/ream', 'description' => ''));
ItemType::create(array( 'itemtype' => 'PAPER MIMEO LONG WHITE WOVE', 'description' => ''));
ItemType::create(array( 'itemtype' => 'PAPER, NEWSPRINT, PICOP LONG; BOOK PAPER, 11" x 17"', 'description' => ''));
ItemType::create(array( 'itemtype' => 'PAPER, MANILA', 'description' => ''));
ItemType::create(array( 'itemtype' => 'WRAPPING PAPER KRAFT (50leaves/pack)  65gsm, approx. 40m', 'description' => ''));
ItemType::create(array( 'itemtype' => 'PENCIL SHARPENER', 'description' => ''));
ItemType::create(array( 'itemtype' => 'PENCIL, MECHANICAL, 0.5 STEADLER', 'description' => ''));
ItemType::create(array( 'itemtype' => 'PUNCHER', 'description' => ''));
ItemType::create(array( 'itemtype' => 'MAP PIN, ROUND HEAD', 'description' => ''));
ItemType::create(array( 'itemtype' => 'PUSH PIN, FLAT HEAD TYPE , ASSORTED COLORS, 100PCS/CASE', 'description' => ''));
ItemType::create(array( 'itemtype' => 'PAPER, MULTICOPY, 80gsm, size: 210mm x 297mm (A4)', 'description' => ''));
ItemType::create(array( 'itemtype' => 'PAPER, RULED PAD, 216MMX330, 90 SHEETS/PAD', 'description' => ''));
ItemType::create(array( 'itemtype' => 'PENCIL, MECHANICAL', 'description' => ''));
ItemType::create(array( 'itemtype' => 'RECORD BOOK , 300 PAGES', 'description' => ''));
ItemType::create(array( 'itemtype' => 'RECORD BOOK , 500 PAGES', 'description' => ''));
ItemType::create(array( 'itemtype' => 'RIBBON, MANUAL TYPEWRITER', 'description' => ''));
ItemType::create(array( 'itemtype' => 'RIBBON FOR FAX KX-FP701 (PANASONIC)', 'description' => ''));
ItemType::create(array( 'itemtype' => 'RIBBON FOR PRINTER, EPSON LQ-2170/2180/2190 ORIGINAL', 'description' => ''));
ItemType::create(array( 'itemtype' => 'RIBBON FR31, TM93011', 'description' => ''));
ItemType::create(array( 'itemtype' => 'RIBBON LX-300/800 PRINTER EPSON ORIGINAL', 'description' => ''));
ItemType::create(array( 'itemtype' => 'RUBBER BAND', 'description' => ''));
ItemType::create(array( 'itemtype' => 'RULER, 12"', 'description' => ''));
ItemType::create(array( 'itemtype' => 'RULER, 18"', 'description' => ''));
ItemType::create(array( 'itemtype' => 'RULER, 24"', 'description' => ''));
ItemType::create(array( 'itemtype' => 'RING BINDER, 12.7mm x 1.12m (1/2"x44"), plastic', 'description' => ''));
ItemType::create(array( 'itemtype' => 'RING BINDER, 19mm x 1.12m(3/4"x44"), plastic', 'description' => ''));
ItemType::create(array( 'itemtype' => 'RING BINDER, 25mm x 1.12m (1"x44"), plastic', 'description' => ''));
ItemType::create(array( 'itemtype' => 'RING BINDER, 50mm x 1.12m(2" x 44"), plastic', 'description' => ''));
ItemType::create(array( 'itemtype' => 'RIBBON FACSIMILE PANASONIC KX-FP342CX', 'description' => ''));
ItemType::create(array( 'itemtype' => 'REGISTRATION CARD', 'description' => ''));
ItemType::create(array( 'itemtype' => 'RIBBON, YMCKO full color, 250 prints/roll', 'description' => ''));
ItemType::create(array( 'itemtype' => 'SCISSORS, 158MM MIN. LENGTH, SYMMETRICAL, JOY BRAND', 'description' => ''));
ItemType::create(array( 'itemtype' => 'SIGNPEN, BLACK, LIQUID GEL INK, 0.5MM NEEDLE TIP, PENTEL ENERJEL BRAND', 'description' => ''));
ItemType::create(array( 'itemtype' => 'SIGNPEN, BLUE, LIQUID GEL INK, 0.5MM NEEDLE TIP, PENTEL ENERJEL BRAND', 'description' => ''));
ItemType::create(array( 'itemtype' => 'SIGNPEN, RED, LIQUID GEL INK, 0.5MM NEEDLE TIP, PENTEL ENERJEL BRAND', 'description' => ''));
ItemType::create(array( 'itemtype' => 'STAMP PAD FELT, BED DIMENSION: 60MM X 100MM MIN', 'description' => ''));
ItemType::create(array( 'itemtype' => 'STAMP PAD, INK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'STAPLE WIRE, ACE', 'description' => ''));
ItemType::create(array( 'itemtype' => 'STAPLE REMOVER', 'description' => ''));
ItemType::create(array( 'itemtype' => 'STAPLER, HEAVY DUTY STANDARD TYPE', 'description' => ''));
ItemType::create(array( 'itemtype' => 'STAPLER, BINDER TYPE', 'description' => ''));
ItemType::create(array( 'itemtype' => 'STAPLE WIRE 23/17', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TAPE DISPENCER, HEAVY DUTY 25MM (1") WIDTH TRANS. TAPE', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TAPE DISPENSER, HAND HELD 48MM', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TAPE MASKING 1" 24MM OLYMPIC', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TAPE MASKING 2" 24MM OLYMPIC', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TAPE, ADDING MACHINE  57M (2-1/4" WIDTH) 55GSM', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TAPE, ELECTRICAL 18MMZ16MM MIN , 25 ROLLS/PACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TAPE, PACKAGING, 1"', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TAPE, TRANSPARENT, width: 48mm (1mm)', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TAPE, TRANSPARENT, width: 48mm (2")', 'description' => ''));
ItemType::create(array( 'itemtype' => 'THUMBSTACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TOILET, TISSUE PAPER, 2PLY SHEET/12RLS /PACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER CARTRIDGE HP 05A , CE505A', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER CARTRIDGE HP KONICA MINOLTA, BISHUB 210', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER CARTRIDGE HP P3010(HP55); TONER CART, HP 55A', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER CARTRIDGE HP OFFICEJET 7000', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER CARTRIDGE FOR HP LASER JET 1100/1100A C4092A BLACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER CARTRIDGE, HP CE285A 1102/ (HP85A), BLACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER CARTRIDGE, HP 15TONER CARTRIDGE FOR HP LASER JET 1200 C7115A BLACK;A', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER CARTRIDGE FOR HP LASER JET 1300/13A', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER CARTRIDGE FOR HP LASER JET 5/6L C3906A/F BLACK; TONER CART, HP 06F, BLACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER CARTRIDGE FOR HP LASER JET 53A  BLACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER CARTRIDGE, HP C9730A, black', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER CARTRIDGE, HP C9731A, cyan', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER CARTRIDGE, HP C9732A, yellow', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER CARTRIDGE, HP C9733A, magenta', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER CARTRIDGE, HP CB540A, BLACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER CARTRIDGE, HP CB541A, CYAN', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER CARTRIDGE, HP CB542A, YELLOW', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER CARTRIDGE, HP CB543A, MAGENTA', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER FOR KYOCERA  KM-1620/TK-410', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER FOR KYOCERA MITA, MODEL KM-2820 (TK-135)', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER FOR KYOCERA 220 (TK 439)', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER FOR KYOCERA LASER PRINTER MODEL FS-1030D (TK-120)', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER FOR KYOCERA LASER PRINTER MODEL FS-820/920(TK 110 E)DSM615/DSM618D885474, 1500', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER CARTRIDGE, DIGITAL MP1500/1600/1900/2000LE (885474)', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER FOR KYOCERA MITA DIGITAL COPIER MODEL KM-2530/3035', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER FOR KYOCERA MITA, MODEL KM-1820 (TK100)', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER FOR KYOCERA, KM-2030', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER GESTETNER, KONICA TN 101/KN 118', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER HP LASERJET PRINT CARTRIDGE 3050/Q26 12A', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER HP LASERJET PRINT CARTRIDGE 35A, CB435A, BLACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER, KYOCERA TK70 9100/9500 SERIES 3050', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TWINE, PLASTIC', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER, BROTHER DCP, DN 7065 DR 225', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER, CARTRIDGE HP #C8543 (9040DN), BLACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TAPE, PACKAGING, 2"', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER, KYOCERA TK-1147', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER, COPIER KYOCERA FS-6525MFP  TK-479', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER, SHARP COPIER MACHINE AR-5520N, AR-021FT', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER, SHARP COPIER MACHINE AR-5520N, AR-021ET', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER, CARTRIDGE HP 127FN, HP83A', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER, CARTIDGE MX-312FT, SHARP COPIER AR-5726', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER CARTRIDGE, MX-23FTBA, BLACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER CARTRIDGE, MX-23FTCA, CYAN', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER CARTRIDGE, MX-23FTMA, MAGENTA', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER CARTRIDGE, MX-23FTYA, YELLOW', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER, KYOCERA ECOSYS FS-1040, TK-1114', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER CARTRIDGE, MX-27FTBA, BLACK', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER CARTRIDGE, MX-27FTCA, CYAN', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER CARTRIDGE, MX-27FTMA, MAGENTA', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER CARTRIDGE, MX-27FTYA, YELLOW', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER, SHARP COPIER MACHINE AR-016 FT', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER CART, HP 43X; TONER CARTRIDGE, MX-238FTI - 3A', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER COPIER, KYOCERA MITA, KM- 1505/1510/1809', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER, MX-62FT-BA', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER, MX-62FT-CA', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER, MX-62FT-MA', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER, MX-62FT-YA', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER CART, HP 124A', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER MX-237-FT', 'description' => ''));
ItemType::create(array( 'itemtype' => 'ULTRACARD PLAIN PVC, 500 PCS/BOX', 'description' => ''));
ItemType::create(array( 'itemtype' => 'WASTE BASKET, NON-RIGID PLASTIC, SQUARE, OVAL OR ROUND SHAPE, ASSORTED COLORS', 'description' => ''));
ItemType::create(array( 'itemtype' => 'INK CART HP 75, COLORED', 'description' => ''));
ItemType::create(array( 'itemtype' => 'COMPUTER CONTINUOUS FORMS, CARBONLESS, 3 PLY, 280 X 378 mm', 'description' => ''));
ItemType::create(array( 'itemtype' => 'TONER,SHARP MX-45FTBA', 'description' => ''));
		
	}
}
